apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-617714
  labels:
    app: nginx-deployment-617714
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-617714
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx-deployment-617714
        tier: frontend
    spec: # Pod spec
      containers:
      - name: nginx-container-617714
        image: nginx:1.21
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-dir
        - mountPath: /var/cache/nginx/client_temp
          name: nginx-empty
        - mountPath: /var/run/
          name: nginx-run  
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nginx-config-617714
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-pvc-617714
        persistentVolumeClaim:
          claimName: nginx-pvc-617714
      - name: nginx-dir
        emptyDir: { }
      - name: nginx-empty
        emptyDir: { }
      - name: nginx-run
        emptyDir: { }
