apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route-617714
  labels:
    app: nginx-deployment-617714
    environment: dev
spec:
  to:
    kind: Service
    name: nginx-service-617714
    weight: 100
  port:
    targetPort: flask
  wildcardPolicy: None
